/** Declaration file generated by dts-gen */

export = site_config;

declare const site_config: {
  author?: string;
  authorBio?: string;
  authorImage?: string;
  brandColor?: string;
  description?: string;
  font?: string;
  fontHeadings?: string;
  footerText?: string;
  googleAnalyticsTrackingId?: string;
  siteUrl: string;
  social: {
    github?: string;
    reddit?: string;
    twitter?: string;
  };
  darkTheme?: string;
  lightTheme?: string;
  title?: string;
};
