// flow-typed signature: af29ebb9dff37b305616ceb5733da4ff
// flow-typed version: <<STUB>>/gatsby-remark-images_v^2.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-remark-images'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-remark-images' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gatsby-remark-images/index' {
  declare module.exports: $Exports<'gatsby-remark-images'>;
}
declare module 'gatsby-remark-images/index.js' {
  declare module.exports: $Exports<'gatsby-remark-images'>;
}
