// flow-typed signature: 2ee628f3198606ec957af93b6e4ede77
// flow-typed version: <<STUB>>/gatsby-image_v^2.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gatsby-image/index' {
  declare module.exports: $Exports<'gatsby-image'>;
}
declare module 'gatsby-image/index.js' {
  declare module.exports: $Exports<'gatsby-image'>;
}
